### ISSUE TITLE
Error when trying to launch the game (UT99 - v436): Execution could not continue. No vulkan surface found

### ISSUE THREAD

**Issue by r-a-sattarov** [dpjudas/SurrealEngine#122]
Hi. When I try to start the game (UT99 version 436), I get the following error:
```
Execution could not continue.
No vulkan surface found
```

Used version aea3429512dc83f0ba49d232ede1fce0fdc4ec07, on OS "Elbrus 8" (Linux 5.10, Mesa 21.3.9, Vulkan 1.2.203).

![1](https://github.com/user-attachments/assets/a94a8f6b-82a3-46af-a259-e468fc0de15e)

![2](https://github.com/user-attachments/assets/84114b54-2412-4200-9e46-d5dd8f3202a3)

![3](https://github.com/user-attachments/assets/e36b9c74-3ada-4a14-ab88-10fc16b41bd2)

**Comment by Xaleros** [comment]
Are you running Wayland or X11?

**Comment by r-a-sattarov** [comment]
> Are you running Wayland or X11?

```
echo $XDG_SESSION_TYPE
x11
```

**Comment by LupertEverett** [comment]
This happens because of some recent changes. We don't have Vulkan surface creation implemented in X11/Wayland backends yet.

In the meantime, SDL2 backend might work, does the game run when you start it with the command given below?

`ZWIDGET_DISPLAY_BACKEND=SDL2 ./SurrealEngine`

**Comment by r-a-sattarov** [comment]
```
ZWIDGET_DISPLAY_BACKEND=SDL2 gdb ./SurrealEngine
GNU gdb (GDB) 9.1-27.023
...
Thread 1 "SurrealEngine" received signal SIGSEGV, Segmentation fault

exc_instr_page_prot at 0x0 

0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000001686d38 in VulkanDeviceBuilder::FindDevices (instance=...) at /home/user/dev/SurrealEngine_08-Jul-2024/Thirdparty/ZVulkan/src/vulkanbuilders.cpp:1674
#2  0x0000000001687748 in VulkanDeviceBuilder::Create (this=0xc2deffffae10, instance=0xc2deffffadf0)
    at /home/user/dev/SurrealEngine_08-Jul-2024/Thirdparty/ZVulkan/src/vulkanbuilders.cpp:1730
#3  0x00000000003f0a20 in VulkanRenderDevice::VulkanRenderDevice (this=0x8a48d80, InViewport=0x811d580, surface=0xc2deffffaee0)
    at /home/user/dev/SurrealEngine_08-Jul-2024/SurrealEngine/RenderDevice/Vulkan/VulkanRenderDevice.cpp:32
#4  0x00000000003ea158 in std::make_unique<VulkanRenderDevice, GameWindow*&, std::shared_ptr<VulkanSurface>&> (__args=..., __args=...)
    at /opt/mcst/lcc-home/1.27.15/e2k-v4-linux/include/c++/g++-v3/bits/unique_ptr.h:862
#5  0x00000000003d8cd0 in RenderDevice::Create (viewport=0x811d580, surface=0xc2deffffb0e0) at /home/user/dev/SurrealEngine_08-Jul-2024/SurrealEngine/RenderDevice/RenderDevice.cpp:10
#6  0x00000000001f74b0 in GameWindow::GameWindow (this=0x811d580, windowHost=0xc2deffffc8b0) at /home/user/dev/SurrealEngine_08-Jul-2024/SurrealEngine/GameWindow.cpp:76
#7  0x00000000002290f8 in std::make_unique<GameWindow, GameWindowHost*&> (__args=@0xc2deffffb148: 0xc2deffffc8b0)
    at /opt/mcst/lcc-home/1.27.15/e2k-v4-linux/include/c++/g++-v3/bits/unique_ptr.h:862
#8  0x00000000001f68b0 in GameWindow::Create (windowHost=0xc2deffffc8b0) at /home/user/dev/SurrealEngine_08-Jul-2024/SurrealEngine/GameWindow.cpp:183
#9  0x0000000000072ef0 in Engine::OpenWindow (this=0xc2deffffc8b0) at /home/user/dev/SurrealEngine_08-Jul-2024/SurrealEngine/Engine.cpp:953
#10 0x00000000000557b0 in Engine::Run (this=0xc2deffffc8b0) at /home/user/dev/SurrealEngine_08-Jul-2024/SurrealEngine/Engine.cpp:70
#11 0x0000000000032c40 in GameApp::main (this=0xc2deffffcf3f, args=0xc2deffffcf60) at /home/user/dev/SurrealEngine_08-Jul-2024/SurrealEngine/GameApp.cpp:32
#12 0x0000000000027ac0 in main (argc=1, argv=0xc2deffffd0a8) at /home/user/dev/SurrealEngine_08-Jul-2024/SurrealEngine/MainGame.cpp:61
```
[surreal-engine-startup-gdb.log](https://github.com/user-attachments/files/16232100/surreal-engine-startup-gdb.log)

**Comment by dpjudas** [comment]
This should be fixed now.

**Comment by r-a-sattarov** [comment]
> This should be fixed now.

Yep, after this commit 7689c486d40f9441b754766cb3d09e674886defd, the game started to run. Thanks!

![1](https://github.com/user-attachments/assets/ebae0abe-de36-4e02-9891-0929544917bf)

![2](https://github.com/user-attachments/assets/7e00dfae-3e23-46e4-b80b-13e8f06a7268)
